### ISSUE TITLE
Recent version - oddities on project's github page

### ISSUE THREAD

**Issue by MarcinOrlowski** [oker1/phpunit_codecoverage_display#29]
There's something wrong here. When I hit: https://github.com/oker1/phpunit_codecoverage_display I see this, pretty ancient page:

![01](https://cloud.githubusercontent.com/assets/8041294/16192213/4e56e942-36e8-11e6-8707-f463d409e0eb.png)

However, hitting "releases" lists "1.0.0" and same when you check "commits". How can I download 1.0.0's JAR? JetBrains repo lists 0.5.0 as the latest available version. https://plugins.jetbrains.com/plugin/6167

**Comment by oker1** [comment]
I've tried to release 1.0.0 yesterday, but had to pull it back because the settings panel is not showing (#28). I tested only from the ide, and it was working, but when it's packaged as jar and installed it doesn't. I will release a new version once I figure it out.

**Comment by rsandimbefore** [comment]
Hi, I'm trying to use PHPUnit code coverage 1.0.0 (because 0.5.0 is not working) with PHPStorm 2016.1.2. When the IDE was starting up the error below was displayed:

```

Plugin 'PHPUnit code coverage' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.ClassNotFoundException: cc.takacs.php_codeverage_display.ApplicationPlugin PluginClassLoader[PHPUnit code coverage, 1.0.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:412)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:61)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I hope it helps..

**Comment by MarcinOrlowski** [comment]
Any chance to have this **extremely useful** plugin back working, please?

**Comment by abrain** [comment]
Version 0.5.0 seems to be working fine in PhpStorm 2018.2, can anyone else confirm?
